= Scala Leipig
:toc:
:toc-placement: preamble

Dieses Projekt enthält Material, Notizen und Tools zur Selbstorganisation der Scala Leipzig User Group.

== Planung

* link:Themen.adoc[Themen]

=== Ankündigungen für Events

* Xing-Gruppe
** Einstellen des Events, offen für alle Xing-Mitglieder
** Event-Einladungen an alle Gruppenmitglieder
* Twitter: Ankündigung des Events mit Link auf Xing-Eventseite
* JUG Saxony: Per Mail an Gruppe (oder Falk Hartmann) Event ankündigen
* Wenn thematisch passend (z.B. Coding Dojo): Ankündigung in Softwerkskammer Sachsen (Portal)
* Aufnahme in den http://typesafe.com/resources/community[Scala-Event-Kalender]: Mail an hello@takipi.com
* Direkte Nachricht an Gruppenunterstützer und Sponsoren

== Kontakt

https://github.com/ScalaLeipzig/orga/[*dieses GitHub Repo*]

Arbeitsmaterial, Notizen, Wiki und Tools zu Organisation der Gruppe.

https://www.xing.com/de/communities/groups/scala-leipzig-980b-1004637[*Xing Gruppe*]

Ankündigung und Verwaltung von Events sowie Forum

https://twitter.com/ScalaLeipzig[*Twitter*]

Ankündigungen von Events und als direkter Feedback-Kanal


== Vergangene Events

=== 2014-06-12: Entwicklung von REST-Services mit Scala, Spray und Akka 


Spray ist ein Toolkit zum Bauen und Verwenden von REST Services,
das auf Akka, einem Aktoren-Framework basiert und inzwischen auch in das Akka Projekt integriert wurde.
Es bietet eine einfache und zugleich mächtige DSL für die Entwicklung von REST-Services.

In dem Vortrag wollen wir, beginnend mit einem leeren Projekt, einen einfachen REST-Service mit Spray bauen
und mit einem Spray-Client verwenden. Da kein Code ohne Tests leben kann, wollen wir natürlich auch zeigen,
wie ein Spray-basierter REST Service getestet werden kann.

Ihr werdet sehen, dass das Bauen von REST-Services sehr einfach sein kann - ohne Container,
Boilerplate und XML - und kurze Entwicklungszeiten ermöglicht. 

* Referent: Tobias Roeser
* https://www.xing.com/events/entwicklung-rest-services-scala-spray-akka-1403829[Offizielle Event-Seite (Xing)]
* Teilnehmer: ca. 20
* https://github.com/lefou/spray-demo[Source Code (GitHub)]
